#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pyroute2.nslink
Version  : 0.6.8
Release  : 14
URL      : https://files.pythonhosted.org/packages/37/4e/f81313ab50f0e7a8e3c60f3e72a35202bdf9fece9e74d94d3c28b66e4f83/pyroute2.nslink-0.6.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/37/4e/f81313ab50f0e7a8e3c60f3e72a35202bdf9fece9e74d94d3c28b66e4f83/pyroute2.nslink-0.6.8.tar.gz
Summary  : Python Netlink library: NetNS, NSPopen and remote modules
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 GPL-2.0+
Requires: pypi-pyroute2.nslink-license = %{version}-%{release}
Requires: pypi-pyroute2.nslink-python = %{version}-%{release}
Requires: pypi-pyroute2.nslink-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pyroute2.core)

%description
pyroute2.nslink
===============
PyRoute2 is a pure Python **netlink** library.
This module provides NetNS, NSPopen and RemoteSocket classes.

%package license
Summary: license components for the pypi-pyroute2.nslink package.
Group: Default

%description license
license components for the pypi-pyroute2.nslink package.


%package python
Summary: python components for the pypi-pyroute2.nslink package.
Group: Default
Requires: pypi-pyroute2.nslink-python3 = %{version}-%{release}

%description python
python components for the pypi-pyroute2.nslink package.


%package python3
Summary: python3 components for the pypi-pyroute2.nslink package.
Group: Default
Requires: python3-core
Provides: pypi(pyroute2.nslink)
Requires: pypi(pyroute2.core)

%description python3
python3 components for the pypi-pyroute2.nslink package.


%prep
%setup -q -n pyroute2.nslink-0.6.8
cd %{_builddir}/pyroute2.nslink-0.6.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647103789
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pyroute2.nslink
cp %{_builddir}/pyroute2.nslink-0.6.8/LICENSE.Apache.v2 %{buildroot}/usr/share/package-licenses/pypi-pyroute2.nslink/cd9bad64b174708395f795bb92f7b4be7d996e8f
cp %{_builddir}/pyroute2.nslink-0.6.8/LICENSE.GPL.v2 %{buildroot}/usr/share/package-licenses/pypi-pyroute2.nslink/4cc77b90af91e615a64ae04893fdffa7939db84c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pyroute2.nslink/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/pypi-pyroute2.nslink/cd9bad64b174708395f795bb92f7b4be7d996e8f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
